// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: proto/film.proto

package film

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilmListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time   string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`     //时间
	Cinema string `protobuf:"bytes,2,opt,name=cinema,proto3" json:"cinema,omitempty"` //电影院
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`     //片名
	Area   string `protobuf:"bytes,4,opt,name=area,proto3" json:"area,omitempty"`     //地区
	Auth   string `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`     //登录验证码
}

func (x *FilmListRequest) Reset() {
	*x = FilmListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_film_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilmListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilmListRequest) ProtoMessage() {}

func (x *FilmListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_film_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilmListRequest.ProtoReflect.Descriptor instead.
func (*FilmListRequest) Descriptor() ([]byte, []int) {
	return file_proto_film_proto_rawDescGZIP(), []int{0}
}

func (x *FilmListRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *FilmListRequest) GetCinema() string {
	if x != nil {
		return x.Cinema
	}
	return ""
}

func (x *FilmListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilmListRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *FilmListRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type FilmInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilmSid int64  `protobuf:"varint,1,opt,name=film_sid,json=filmSid,proto3" json:"film_sid,omitempty"` //电影场次id
	Auth    string `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`                       //登录验证码
}

func (x *FilmInfoRequest) Reset() {
	*x = FilmInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_film_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilmInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilmInfoRequest) ProtoMessage() {}

func (x *FilmInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_film_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilmInfoRequest.ProtoReflect.Descriptor instead.
func (*FilmInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_film_proto_rawDescGZIP(), []int{1}
}

func (x *FilmInfoRequest) GetFilmSid() int64 {
	if x != nil {
		return x.FilmSid
	}
	return 0
}

func (x *FilmInfoRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type Respone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respone []byte `protobuf:"bytes,1,opt,name=respone,proto3" json:"respone,omitempty"`
}

func (x *Respone) Reset() {
	*x = Respone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_film_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respone) ProtoMessage() {}

func (x *Respone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_film_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respone.ProtoReflect.Descriptor instead.
func (*Respone) Descriptor() ([]byte, []int) {
	return file_proto_film_proto_rawDescGZIP(), []int{2}
}

func (x *Respone) GetRespone() []byte {
	if x != nil {
		return x.Respone
	}
	return nil
}

var File_proto_film_proto protoreflect.FileDescriptor

var file_proto_film_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x0f, 0x46, 0x69, 0x6c,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x65, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x75, 0x74, 0x68, 0x22, 0x40, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x5f,
	0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x6d, 0x53,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x23, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x32, 0xb7, 0x01, 0x0a, 0x0b,
	0x46, 0x69, 0x6c, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x66, 0x69, 0x6c, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_film_proto_rawDescOnce sync.Once
	file_proto_film_proto_rawDescData = file_proto_film_proto_rawDesc
)

func file_proto_film_proto_rawDescGZIP() []byte {
	file_proto_film_proto_rawDescOnce.Do(func() {
		file_proto_film_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_film_proto_rawDescData)
	})
	return file_proto_film_proto_rawDescData
}

var file_proto_film_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_film_proto_goTypes = []interface{}{
	(*FilmListRequest)(nil), // 0: proto.FilmListRequest
	(*FilmInfoRequest)(nil), // 1: proto.FilmInfoRequest
	(*Respone)(nil),         // 2: proto.Respone
}
var file_proto_film_proto_depIdxs = []int32{
	0, // 0: proto.FilmService.GetAllList:input_type -> proto.FilmListRequest
	0, // 1: proto.FilmService.GetInfoList:input_type -> proto.FilmListRequest
	1, // 2: proto.FilmService.GetHallInfo:input_type -> proto.FilmInfoRequest
	2, // 3: proto.FilmService.GetAllList:output_type -> proto.Respone
	2, // 4: proto.FilmService.GetInfoList:output_type -> proto.Respone
	2, // 5: proto.FilmService.GetHallInfo:output_type -> proto.Respone
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_film_proto_init() }
func file_proto_film_proto_init() {
	if File_proto_film_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_film_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilmListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_film_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilmInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_film_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_film_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_film_proto_goTypes,
		DependencyIndexes: file_proto_film_proto_depIdxs,
		MessageInfos:      file_proto_film_proto_msgTypes,
	}.Build()
	File_proto_film_proto = out.File
	file_proto_film_proto_rawDesc = nil
	file_proto_film_proto_goTypes = nil
	file_proto_film_proto_depIdxs = nil
}
